-- TRIPPICK customer-site baseline.
-- The public host console is a static portfolio demo and does not query these tables.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 1 and 50),
  site_id text not null check (char_length(site_id) between 1 and 160),
  site_name text not null check (char_length(site_name) between 1 and 120),
  rating smallint not null check (rating between 1 and 5),
  title text not null check (char_length(title) between 1 and 160),
  body text not null check (char_length(body) between 1 and 4000),
  photos jsonb not null default '[]'::jsonb check (jsonb_typeof(photos) = 'array'),
  admin_reply text check (admin_reply is null or char_length(admin_reply) <= 2000),
  status text not null default 'visible' check (status in ('visible', 'pending', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reviews_user_created_idx on public.reviews (user_id, created_at desc);
create index if not exists reviews_site_visible_idx on public.reviews (site_id, created_at desc) where status = 'visible';

alter table public.reviews enable row level security;

drop policy if exists reviews_visible_to_anon on public.reviews;
create policy reviews_visible_to_anon on public.reviews
  for select to anon
  using (status = 'visible');

drop policy if exists reviews_visible_or_owned on public.reviews;
create policy reviews_visible_or_owned on public.reviews
  for select to authenticated
  using (status = 'visible' or (select auth.uid()) = user_id);

drop policy if exists reviews_insert_own on public.reviews;
create policy reviews_insert_own on public.reviews
  for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists reviews_update_own on public.reviews;
create policy reviews_update_own on public.reviews
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists reviews_delete_own on public.reviews;
create policy reviews_delete_own on public.reviews
  for delete to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 2 and 50),
  category text not null check (category in ('예약', '시설', '취소/환불', '기타')),
  title text not null check (char_length(title) between 1 and 160),
  body text not null check (char_length(body) between 1 and 4000),
  is_secret boolean not null default false,
  status text not null default 'published' check (status in ('published', 'hidden')),
  admin_answer text check (admin_answer is null or char_length(admin_answer) <= 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists board_posts_user_created_idx on public.board_posts (user_id, created_at desc);
create index if not exists board_posts_public_created_idx on public.board_posts (created_at desc) where status = 'published';

alter table public.board_posts enable row level security;

drop policy if exists board_posts_select_own on public.board_posts;
create policy board_posts_select_own on public.board_posts
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists board_posts_insert_own on public.board_posts;
create policy board_posts_insert_own on public.board_posts
  for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists board_posts_update_own on public.board_posts;
create policy board_posts_update_own on public.board_posts
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists board_posts_delete_own on public.board_posts;
create policy board_posts_delete_own on public.board_posts
  for delete to authenticated
  using ((select auth.uid()) = user_id);

-- Public listing deliberately redacts every secret body. This function is read-only,
-- uses a fixed search_path, and has an explicit grant list.
create or replace function public.list_board_posts()
returns table (
  id bigint,
  author_name text,
  category text,
  title text,
  body text,
  is_secret boolean,
  admin_answer text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    post.id,
    post.author_name,
    post.category,
    post.title,
    case when post.is_secret then null else post.body end,
    post.is_secret,
    case when post.is_secret then null else post.admin_answer end,
    post.created_at
  from public.board_posts as post
  where post.status = 'published'
  order by post.created_at desc
  limit 100;
$$;

revoke all on public.reviews, public.board_posts from anon, authenticated;
grant select on public.reviews to anon;
grant select, insert, update, delete on public.reviews to authenticated;
grant select, insert, update, delete on public.board_posts to authenticated;
grant usage, select on sequence public.reviews_id_seq, public.board_posts_id_seq to authenticated;

revoke execute on function public.list_board_posts() from public;
grant execute on function public.list_board_posts() to anon, authenticated;
